/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KoRouteImport } from './routes/ko'
import { Route as StudyRouteImport } from './routes/study'
import { Route as ApiPublishRouteImport } from './routes/api.publish'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoRoute = KoRouteImport.update({
  id: '/ko',
  path: '/ko',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishRoute = ApiPublishRouteImport.update({
  id: '/api/publish',
  path: '/api/publish',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ko': typeof KoRoute
  '/study': typeof StudyRoute
  '/api/publish': typeof ApiPublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ko': typeof KoRoute
  '/study': typeof StudyRoute
  '/api/publish': typeof ApiPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ko': typeof KoRoute
  '/study': typeof StudyRoute
  '/api/publish': typeof ApiPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ko' | '/study' | '/api/publish'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ko' | '/study' | '/api/publish'
  id: '__root__' | '/' | '/ko' | '/study' | '/api/publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KoRoute: typeof KoRoute
  StudyRoute: typeof StudyRoute
  ApiPublishRoute: typeof ApiPublishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko': {
      id: '/ko'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish': {
      id: '/api/publish'
      path: '/api/publish'
      fullPath: '/api/publish'
      preLoaderRoute: typeof ApiPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KoRoute: KoRoute,
  StudyRoute: StudyRoute,
  ApiPublishRoute: ApiPublishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
